/**
 * session-manager.js
 * Manages persistent user authentication sessions for Instagram and YouTube in StreamDock.
 * Generates and stores standard Netscape cookies.txt files without relying on browser DPAPI.
 */

const fs = require('fs');
const path = require('path');

function getSessionDirectory() {
  const appData = process.env.APPDATA || process.env.HOME || process.env.USERPROFILE || '.';
  const sessionDir = path.join(appData, 'StreamDock');
  if (!fs.existsSync(sessionDir)) {
    try {
      fs.mkdirSync(sessionDir, { recursive: true });
    } catch (e) {
      console.warn('Could not create session directory in APPDATA, falling back to local dir', e);
      return path.resolve('.');
    }
  }
  return sessionDir;
}

function getInstagramSessionFilePath() {
  return path.join(getSessionDirectory(), 'instagram_session.txt');
}

/**
 * Generates a standard Netscape cookies.txt file from raw cookie input or sessionid
 * @param {string} cookieInput
 * @returns {string} Path to the created session file
 */
function saveInstagramSession(cookieInput) {
  if (!cookieInput || typeof cookieInput !== 'string' || !cookieInput.trim()) {
    clearInstagramSession();
    return '';
  }

  const filePath = getInstagramSessionFilePath();
  const trimmed = cookieInput.trim();

  // If already in full Netscape format
  if (trimmed.includes('# Netscape') || trimmed.includes('.instagram.com\t')) {
    fs.writeFileSync(filePath, trimmed + '\n', 'utf8');
    return filePath;
  }

  let lines = [
    '# Netscape HTTP Cookie File',
    '# http://curl.haxx.se/rfc/cookie_spec.html',
    '# Generated by StreamDock - Persistent Instagram Session',
    ''
  ];

  const expiry = Math.floor(Date.now() / 1000) + (365 * 24 * 60 * 60); // 1 year validity

  // If user pasted document.cookie string (key=value; key2=value2)
  if (trimmed.includes('=')) {
    const parts = trimmed.split(';');
    for (const part of parts) {
      const idx = part.indexOf('=');
      if (idx > -1) {
        const name = part.substring(0, idx).trim();
        const value = part.substring(idx + 1).trim();
        if (name && value) {
          lines.push(`.instagram.com\tTRUE\t/\tTRUE\t${expiry}\t${name}\t${value}`);
        }
      }
    }
  } else {
    // User pasted just the raw sessionid token
    lines.push(`.instagram.com\tTRUE\t/\tTRUE\t${expiry}\tsessionid\t${trimmed}`);
    lines.push(`.instagram.com\tTRUE\t/\tTRUE\t${expiry}\tds_user_id\t12345678`);
  }

  fs.writeFileSync(filePath, lines.join('\n') + '\n', 'utf8');
  return filePath;
}

/**
 * Checks if a valid Instagram session file exists
 * @returns {boolean}
 */
function hasInstagramSession() {
  const filePath = getInstagramSessionFilePath();
  if (!fs.existsSync(filePath)) return false;
  try {
    const stat = fs.statSync(filePath);
    return stat.size > 20;
  } catch (e) {
    return false;
  }
}

/**
 * Deletes the saved Instagram session
 */
function clearInstagramSession() {
  const filePath = getInstagramSessionFilePath();
  if (fs.existsSync(filePath)) {
    try {
      fs.unlinkSync(filePath);
    } catch (e) {
      console.warn('Could not delete session file:', e);
    }
  }
}

module.exports = {
  getSessionDirectory,
  getInstagramSessionFilePath,
  saveInstagramSession,
  hasInstagramSession,
  clearInstagramSession
};
